package main

import (
	"encoding/json"
	"fmt"
)

//Starting with this code, unmarshal the JSON into a Go data structure. Hint: https://mholt.github.io/json-to-go/


func main() {
	s := `[{"first":"James","Last":"Bond","Age":32,"Sayings":["Shaken, not stirred","Youth is no guarantee of innovation","In his majesty's royal service"]},{"first":"Miss","Last":"Moneypenny","Age":27,"Sayings":["James, it is soo good to see you","Would you like me to take care of that for you, James?","I would really prefer to be a secret agent myself."]},{"first":"M","Last":"Hmmmm","Age":54,"Sayings":["Oh, James. You didn't.","Dear God, what has James done now?","Can someone please tell me where James Bond is?"]}]`
	fmt.Println(s)



	type AutoGenerated struct {
		First   string   `json:"first"`
		Last    string   `json:"Last"`
		Age     int      `json:"Age"`
		Sayings []string `json:"Sayings"`
	}

	//var ju AutoGenerated
	var ju []AutoGenerated
	fmt.Println("---------------")

	err := json.Unmarshal([]byte(s), &ju)
	if err != nil {
		fmt.Println("error", err)
		return
	}
	fmt.Println(ju)
}
